"""Required edge cases (spec section 8). Names map 1:1 to the course list.
Implement each body in Phase 6 with hand-derived expectations.
"""
import pytest

TODO = pytest.mark.skip(reason="TODO Phase 6")


@TODO
def test_empty_sequence(): ...
@TODO
def test_one_character_sequence(): ...
@TODO
def test_empty_motif_rejected(): ...
@TODO
def test_motif_longer_than_sequence(): ...
@TODO
def test_no_match(): ...
@TODO
def test_single_exact_match(): ...
@TODO
def test_multiple_matches(): ...
@TODO
def test_overlapping_matches(): ...
@TODO
def test_repeated_single_character_sequence(): ...
@TODO
def test_invalid_sequence_characters(): ...
@TODO
def test_invalid_motif_characters(): ...
@TODO
def test_motif_equals_whole_sequence(): ...
@TODO
def test_stress_case_AAAAAAAB(): ...   # predict BEFORE running; see decision/dev log
